name = "PolyPack"
author = "TrueCP5"
version = "0.3.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "542d9966dfb09872f310d149b975a89ba15f2e750cec10cdd88af1c54bec9b80"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "35.1.12"
jumploader-version-id = 3103389
project-id = 0
