name = "PolyPack"
author = "TrueCP5"
version = "0.3.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70138b8845f0b611eeaf77624025c663a25cbcae4dcefeefbe3c8296fb32817f"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "35.1.12"
jumploader-version-id = 3103389
project-id = 0
