name = "PolyPack"
author = "TrueCP5"
version = "0.3.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11896d36e3f95139233b163b7d8b7384745d4661ca07d8d5cab15387232b3cf5"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "35.1.12"
jumploader-version-id = 3103389
project-id = 0
