name = "PolyPack"
author = "TrueCP5"
version = "0.3.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07e014494e6bff3a11e4ce3070dafe1d41c7640f18d431cdc7d06aa36c88f73e"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "35.1.12"
jumploader-version-id = 3103389
project-id = 0
