name = "PolyPack"
author = "TrueCP5"
version = "0.3.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d112def764c75488464a42a351ba331e3c66918e1329c1ceeafa83c1c856f749"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "35.1.12"
jumploader-version-id = 3103389
project-id = 0
